language: ruby
rvm:
  - 2.2.4
env:
  - DB=sqlite
script:
  - bundle exec rspec  
before_script:
  - gem install bundler
  - export RAILS_ENV=test
  - bundle install
  - bundle exec  rake app:db:create app:db:migrate RAILS_ENV=test
